#!/usr/bin/env node
'use strict';

const	uuidLib	= require('uuid/v4'),
	processUuid	= uuidLib(),
	spawn	= require('child_process').spawn,
	argv	= require('minimist')(process.argv.slice(2)),
	ipc	= require('node-ipc');

let	indexName	= argv._[0] || false,
	typeName	= argv._[1] || false,
	esProt	= argv.protocoll	|| 'http',
	esHost	= argv.h || '127.0.0.1',
	esPort	= argv.P || '9200',
	esUrl	= esProt + '://' + esHost + ':' + esPort + '/';

ipc.config.id	= 'esdump_' + processUuid;
ipc.config.silent	= true;

ipc.serve(function () {
	spawn('node', [__dirname + '/esCaller.js',	ipc.config.id, esUrl, indexName, typeName]);
	//spawn('node', [__dirname + '/processEsCall.js',	ipc.config.id]);

	ipc.server.on('message', function (data, socket) {
		ipc.server.emit(socket, 'message', data + ' world!');
	});
});

ipc.server.start();
//ipc.server.stop();